
name: Build and Deploy to Docker hub

on:
  push:
    branches: 
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        echo ${{ secrets.DOCKER_HUB }} | docker login -u mikailbag --password-stdin 
    - name: Build
      run: |        
        docker build -t mikailbag/kube-dump:latest -f Cargo.toml .
    - name: Publish
      run: |
        docker push mikailbag/kube-dump:latest
